jobs:
  - name: make dough
    plan:
      - get: dough
      - put: pizza
        params:
          from: dough/dough.png
  - name: chop peppers
    plan:
      - get: green-pepper

  - name: slice pepperoni
    plan:
      - get: pepperoni

  - name: grate cheese
    plan:
      - get: cheese
        trigger: true

  - name: prep toppings
    plan:
      - aggregate:
        - get: pizza-pipeline
        - get: green-pepper
          passed: ["chop peppers"]
        - get: cheese
          passed: ["grate cheese"]
          trigger: true
        - get: pepperoni
          passed: ["slice pepperoni"]
      - task: prep
        file: pizza-pipeline/tasks/prep-toppings/task.yml
      - put: toppings
        params:
          file: ingredients/ingredients.png

  - name: add toppings to pizza
    plan:
      - aggregate:
        - get: pizza-pipeline
        - get: toppings
          trigger: true
          passed: ["prep toppings"]
        - get: pizza
          passed: ["make dough"]
      - task: add-toppings
        file: pizza-pipeline/tasks/add-toppings/task.yml
      - put: pizza
        params:
          file: topped-pizza/pizza.png
  - name: deliver pizza
    plan:
      - aggregate:
        - get: pizza-pipeline
        - get: pizza
          trigger: true
          passed: ["add toppings to pizza"]
      - task: box-pizza
        file: pizza-pipeline/tasks/box-pizza/task.yml
      - put: pws
        params:
          path: boxed-pizza
          manifest: boxed-pizza/manifest.yml

resources:

- name: pizza
  type: s3
  source:
    bucket: concourse-demo-bucket
    versioned_file: pizza.png
    private: true
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
- name: dough
  type: s3
  source:
    private: true
    bucket: concourse-demo-bucket
    versioned_file: dough.png
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
- name: pepperoni
  type: s3
  source:
    private: true
    bucket: concourse-demo-bucket
    versioned_file: ingredients/pepperoni.png
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: green-pepper
  type: s3
  source:
    private: true
    bucket: concourse-demo-bucket
    versioned_file: ingredients/green_pepper.png
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: cheese
  type: s3
  source:
    private: true
    bucket: concourse-demo-bucket
    versioned_file: ingredients/sauce.png
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: toppings
  type: s3
  source:
    private: true
    bucket: concourse-demo-bucket
    versioned_file: toppings/toppings.png
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: pizza-pipeline
  type: git
  source:
    branch: master
    private_key: {{github-key}}
    uri: git@github.com:pivotal-topher-bullock/concourse-pizza-pipeline-demo.git

- name: pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
